import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://pro.fontawesome.com/releases/v5.15.0/css/all.css"
                />
            </head>
            <body>
                <div className="flex justify-center items-center h-screen bg-white p-0 sm:p-6">
                    <div className="relative w-[450px] h-full rounded-none sm:rounded-xl bg-gradient-to-t from-[#1472FF] to-[#92E5FF] shadow-lg px-6 overflow-hidden">
                        <div className="absolute bottom-[-176px] left-1/2 -translate-x-1/2 min-w-[120vw] min-h-[120vw] sm:min-w-[500px] sm:min-h-[500px] rounded-full bg-white">

                        </div>
                        <div className="relative h-full">{children}</div>
                    </div>
                </div>
            </body>
        </html>
    );
}
