import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "PiggyPocket",
    description: "Generated by create next app",
    icons: {
        icon: "/images/pig_1.png"
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://pro.fontawesome.com/releases/v5.15.0/css/all.css"
                />
            </head>
            <body>
                <div className="flex justify-center items-center sm:h-screen bg-white p-0 sm:p-6">
                    <div className="relative w-[450px] h-[100dvh] sm:h-full rounded-none sm:rounded-xl bg-gradient-to-t from-[#1472FF] to-[#92E5FF] shadow-none sm:shadow-lg px-6 overflow-hidden">
                        <Navbar />
                        <div className="absolute bottom-[-176px] left-1/2 -translate-x-1/2 min-w-[120vw] min-h-[120vw] sm:min-w-[500px] sm:min-h-[500px] rounded-full bg-white"></div>
                        <div className="relative h-full">{children}</div>
                    </div>
                </div>
            </body>
        </html>
    );
}
